#!/bin/zsh

# emacs mode
bindkey -e

if [ -n "$ZSH_VERSION" ]; then
  if [ -f /usr/local/opt/chruby/share/chruby/chruby.sh ]; then
    # OSX - homebrew
    source /usr/local/opt/chruby/share/chruby/chruby.sh
    source /usr/local/opt/chruby/share/chruby/auto.sh
  fi
fi

if which direnv>/dev/null; then
  eval "$(direnv hook zsh)"
fi

