#!/bin/bash
alias be='bundle exec '
alias gs='git status '
alias gap='git add -p'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gk='gitk --all&'
alias glodag='git log --all --decorate --graph --oneline'
alias sshfs-sdf='sshfs agarren@sdf.lonestar.org:/sdf/arpa/af/a/agarren/docs ~/mnt/sdf -o defer_permissions -o volname=Server'

docker-prune () {
  docker rmi $(docker images | grep "none" | awk '{print $3}')
}

markdown () {
  pandoc -f markdown -t html $1 | sed s/[”“]/'"'/g | lynx -stdin
}

alias go_c="gcc -xc -std=c99 '-' $go_libs $go_flags"

if [ -x /usr/bin/dircolors ]; then
    alias ls='ls --color=auto'
fi

alias ll='ls -l'
alias la='ls -a'
alias lla='ls -al'

# full color tmux terminal for vim colorscheme support
#alias tmux="TERM=screen-256color-bce tmux"
alias ssh='TERM=xterm-256color ssh'

if [[ "$OSTYPE" == 'linux-gnu' ]]; then
  alias gx='gitx --all'
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
elif [[ "$OSTYPE" == 'darwin'* ]]; then
  alias flushdns='sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder && say DNS cache flushed'
fi

if [ -d /keybase/private/garren ]; then
  function lb() {
    if [ -z "$1" ]; then
      vim /keybase/private/garren/logbook/$(date '+%Y-%m-%d').md
    else
      vim /keybase/private/garren/logbook/tool-$1.md
    fi
  }
fi
