#!/bin/bash

if [ -f /usr/local/opt/chruby/share/chruby/chruby.sh ]; then
  source /usr/local/opt/chruby/share/chruby/chruby.sh
  source /usr/local/opt/chruby/share/chruby/auto.sh
fi

function parse_git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}")"
}

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f /Users/adamgarren/.node_packages/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash ] && . /Users/adamgarren/.node_packages/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f /Users/adamgarren/.node_packages/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash ] && . /Users/adamgarren/.node_packages/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[ -f /Users/adamgarren/.node_packages/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.bash ] && . /Users/adamgarren/.node_packages/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.bash
